In [12]:
import numpy as np
import pandas as pd

In [13]:
x=[1,2,3,4]

In [17]:
x=np.array(x)
x

array([1, 2, 3, 4])

In [27]:
x.astype(type(1))

array([1, 2, 3, 4])

In [29]:
slice=x[0:2]
slice

array([1, 2])